# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzUrFO3xNKOUNQ6yODXs-QVoBE1mEKOw
"""

import numpy as np
n1=np.array([1,2,3])
print(n1)

n2=np.array([[1,2,3],[4,5,6]])
print(n2)

#zero filled in 2d array
n3=np.zeros([3,3],dtype='i4')
print(n3)

#fills with ones
n4=np.ones([2,3,3],dtype='i4')
print(n4)

# empty array
n5=np.empty([3,3])
print(n5)

# range fills in the array
n6=np.arange(10)
print(n6)

# numpy .orgs can see the all ranges

n7=np.arange(-5,10,5)
print(n7)

# Linearly spaced entries
n8=np.linspace(0,20,num=8,dtype='i4')
print(n8)

# Fill the array
n5.fill(10)
print(n5)

# Full the array
n9=np.full([2,5],99)
print(n9)

# Accessing
print(n1[0])

print(n1[-1])

print(n2[1,0])

print(n2[1,:])

print(n2[:,1])

print(n4[1,2,0])

n4[1,2,0]=10
print(n4)

# Sixze and Shape
print(n4.ndim)

print(n4.shape)

print(n4.size)

print(n4.dtype)

print(n4.itemsize)

print(n4.nbytes)

# SORTING
n10=np.array([5, 1, 3, 6, 7, 9, 5,6])
np.sort(n10)

n11=np.array([[6 ,3, 7],[1, 3, 2]])
np.sort(n11)

np.sort(n11,axis=0)

np.sort(n11,axis=1)

# RESHAPPING and ARRAY CONVERSIONS
n12=n10.reshape(2,4)
print(n12)

# join two array using concate

n13=np.arange(4)
print(n13)
n14=np.arange(5,9)
print(n14)
n15=np.concatenate((n13,n14))
print(n15)

n16=np.arange(8)
print(n16)
n17=n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)

n19=np.expand_dims(n16,axis=1)
print(n19)

# Indexing and Slicing
n21=np.arange(10)
print(n21)
print(n21[n21<5])

print(n21[(n21>3) &(n21<8)])

five_up=n21>5
print(five_up)
print(n21[five_up])

n21[6]=100
print(np.nonzero(n21>5))

print(n21[3:7])

# Stack,Split
n22=np.array([[1,2],[3,4]])
n23=np.array([[6,7],[8,9]])
np.hstack((n22,n23))

np.vstack((n22,n23))

n24=np.arange(20)
print(n24)
np.hsplit(n24,4)

# copy
n25=n24[0:5] #shallow copy
n24[0]=23
print(n24)
print(n25)

# deep copy
n26=n24.copy()
n24[0]=3444
print(n26)
print(n24)

# MAth
print(n22)
print(n23)
print(n22+n23)

print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)
print(np.cos(n26))

# Random Numbers
np.random.rand(3,3)

np.random.randint(20,size=(4,2))